[package]
name = "testez"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
inquire = "0.7.5"
reqwest = "0.12.7"
yaml-rust = { version = "0.9", package = "yaml-rust2" }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
